### ISSUE TITLE
Errors with DDQN

### ISSUE THREAD

**Issue by HappyDay-design** [parasnaren/AI-Traffic-Light-Control#1]
Hello
Your code is very useful.
I can run DQN but I had errors with DDQN
Could you show your TensorFlow version?
Thank you

(DRL) C:\Users\PKNU\Desktop\AI-Traffic-Light-Control\DDQN>C:/Users/PKNU/anaconda3/envs/DRL/python.exe c:/Users/PKNU/Desktop/AI-Traffic-Light-Control/DDQN/training_main.py
Traceback (most recent call last):
  File "c:/Users/PKNU/Desktop/AI-Traffic-Light-Control/DDQN/training_main.py", line 33, in <module>   
    set_session(get_session())
  File "c:\Users\PKNU\Desktop\AI-Traffic-Light-Control\DDQN\utils\networks.py", line 9, in get_session
    config.gpu_options.allow_growth = True
AttributeError: '_FieldProperty' object has no attribute 'allow_growth'

**Comment by HappyDay-design** [comment]
Now, I can run DDQN with
tensorflow==1.13.1
keras==2.2.4
on Ubuntu

**Comment by parasnaren** [comment]
Thanks, can you create a merge request to update the same on the repo?

Thanks,
Paras

**Comment by HappyDay-design** [comment]
Hello. I do not know to create a merge request :(. I comment here so that anyone can follow and run this model.
Thank you for sharing your code
